name: Reaload bot
on: [push]
jobs:
  reload:
    runs-on: [self-hosted, linux]
    steps:
      - run: pwd
      - run: ls -a -l
      - run: source env/bin/activate.sh
      - run: nohup python3 main.py
