name: Reload bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reload:
    runs-on: [self-hosted, linux]
    steps:
      - name: Go to the bot directory
        run : cd ~/Dijkstra-Chan
      - name: Set up Python environnement
        run: |
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pull and switch to main branch
        run: |
          git pull --recurse-submodules origin main
          git checkout main
      - name: Shutdown bot
        continue-on-error: true
        run: killall python
      - name: Run bot
        env:
          RUNNER_TRACKING_ID: ""
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        run: nohup python main.py &
