name: Reload bot

on:
  push:
  workflow_dispatch:

jobs:
  reload:
    runs-on: [self-hosted, linux]
    steps:
      - name: Go to the bot directory
        run : cd ~/Dijkstra-Chan
      - name: Set up python environnement
        run: |
          source env/bin/activate
          pip install -r requirements.txt
      - name: Checkout repository and submodules
        run: git pull --recurse-submodules
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        run: RUNNER_TRACKING_ID="" && nohup python main.py &
